# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawfish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField()),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='LevelWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_id', models.IntegerField()),
                ('word_id', models.IntegerField()),
            ],
            options={
                'db_table': 'level_words',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word_id', models.IntegerField()),
                ('content', models.TextField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField()),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
