# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawfish', '0002_auto_20160630_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
